export enum NotificationTriggerType {
	STATEMENT_REPLY = 'statement_reply',
	SOCIAL_PROOF = 'social_proof',
	CONSENSUS_SHIFT = 'consensus_shift',
	VOTING_DEADLINE = 'voting_deadline',
	DAILY_DIGEST = 'daily_digest',
	WEEKLY_DIGEST = 'weekly_digest',
	CREDIT_EARNED = 'credit_earned',
	LEVEL_UP = 'level_up',
	BADGE_EARNED = 'badge_earned',
	STREAK_REMINDER = 'streak_reminder',
	WELCOME_BACK = 'welcome_back',
	EVIDENCE_ADDED = 'evidence_added',
	MENTION = 'mention',
	// Agora classroom game
	AGORA_SUGGESTION_RECEIVED = 'agora_suggestion_received',
	AGORA_SUGGESTION_ACCEPTED = 'agora_suggestion_accepted',
	AGORA_SUGGESTION_THANKED = 'agora_suggestion_thanked',
	AGORA_ROUND_STARTED = 'agora_round_started',
}
