/**
 * Seed 40 raw benchmark options with LIVE-SYNTH DISABLED (emulator only).
 *
 * Unlike scripts/seedSynthBenchmark.ts (which enables synthesis so the live
 * pipeline clusters as options arrive), this writes clean raw options only.
 * Embeddings are still generated by the standalone `fn_statementCreation`
 * trigger (Task 6), independent of synthesis. The bulk rebuild
 * (bulkRebuild.ts) then clusters them disjointly in one pass.
 *
 * Idempotent: if 40 options already exist under the question it skips seeding
 * and just waits for embedding coverage.
 *
 * USAGE (from functions/):
 *   FIRESTORE_EMULATOR_HOST=localhost:8081 GCLOUD_PROJECT=freedi-test \
 *     npx tsx scripts/cleanRawSeed.ts <questionId> <benchmark.json> "<question text>"
 */
import { readFileSync } from 'node:fs';
import { initializeApp, getApps } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

if (!process.env.FIRESTORE_EMULATOR_HOST) {
	console.error('Refusing to run without FIRESTORE_EMULATOR_HOST set. Emulator-only.');
	process.exit(1);
}
const questionId = process.argv[2];
const benchmarkPath = process.argv[3];
const questionText = process.argv[4] ?? 'How can we all be happy (2)?';
if (!questionId || !benchmarkPath) {
	console.error('Usage: npx tsx scripts/cleanRawSeed.ts <questionId> <benchmark.json> "<text>"');
	process.exit(1);
}
if (getApps().length === 0) {
	initializeApp({ projectId: process.env.GCLOUD_PROJECT ?? 'freedi-test' });
}
const db = getFirestore();
const USER_UID = process.env.SEED_USER_UID ?? 'dDKeLPe8IC6EOttQ5Ih6Y9ZXcXfY';
const DELAY_MS = Number(process.env.SEED_DELAY_MS ?? 1500);

interface Benchmark {
	topics: Array<{ name: string; synths: Array<{ name: string; paraphrases: string[] }> }>;
}
const benchmark: Benchmark = JSON.parse(readFileSync(benchmarkPath, 'utf-8'));

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const blankEval = () => ({
	sumEvaluations: 0,
	numberOfEvaluators: 0,
	sumPro: 0,
	sumCon: 0,
	numberOfProEvaluators: 0,
	numberOfConEvaluators: 0,
	sumSquaredEvaluations: 0,
	averageEvaluation: 0,
	agreement: 0,
	evaluationRandomNumber: Math.random(),
	viewed: 0,
});

async function ensureQuestion(): Promise<void> {
	const ref = db.collection('statements').doc(questionId);
	const snap = await ref.get();
	const now = Date.now();
	// Explicitly DISABLE synthesis so the live pipeline does not fire on writes.
	const settings = {
		enableAddVotingOption: true,
		enableAddEvaluationOption: true,
		enableNotifications: false,
		synthesis: { enabled: false },
		liveSynthEnabled: false,
	};
	if (snap.exists) {
		console.info(`✓ Question ${questionId} exists — forcing synthesis OFF`);
		await ref.set({ statementSettings: settings, lastUpdate: now }, { merge: true });

		return;
	}
	console.info(`+ Creating question ${questionId} (synthesis OFF)`);
	await ref.set({
		statementId: questionId,
		statement: questionText,
		paragraphs: [],
		statementType: 'question',
		parentId: 'top',
		parents: [],
		topParentId: questionId,
		creatorId: USER_UID,
		creator: { uid: USER_UID, displayName: 'Clean Seeder', email: 'clean@example.com', photoURL: null, isAnonymous: false, defaultLanguage: 'en' },
		createdAt: now,
		lastUpdate: now,
		lastChildUpdate: now,
		consensus: 0,
		totalEvaluators: 0,
		hide: false,
		randomSeed: Math.random(),
		evaluation: blankEval(),
		membership: { access: 'public' },
		statementSettings: settings,
	});
}

async function seedOptions(): Promise<void> {
	const existing = await db.collection('statements').where('parentId', '==', questionId).where('statementType', '==', 'option').get();
	const rawExisting = existing.docs.filter((d) => !d.data().derivedByPipeline);
	if (rawExisting.length >= 40) {
		console.info(`✓ ${rawExisting.length} raw options already present — skipping seed`);

		return;
	}
	const flat: string[] = [];
	for (const t of benchmark.topics) for (const s of t.synths) for (const p of s.paraphrases) flat.push(p);
	console.info(`Writing ${flat.length} raw options (delay=${DELAY_MS}ms)…`);
	for (let i = 0; i < flat.length; i++) {
		const id = db.collection('statements').doc().id;
		const now = Date.now();
		await db.collection('statements').doc(id).set({
			statementId: id,
			statement: flat[i],
			paragraphs: [],
			statementType: 'option',
			parentId: questionId,
			parents: [questionId],
			topParentId: questionId,
			creatorId: USER_UID,
			creator: { uid: USER_UID, displayName: 'Clean Seeder', email: 'clean@example.com', photoURL: null, isAnonymous: false, defaultLanguage: 'en' },
			createdAt: now,
			lastUpdate: now,
			consensus: 0,
			totalEvaluators: 0,
			hide: false,
			randomSeed: Math.random(),
			evaluation: blankEval(),
		});
		if (i + 1 < flat.length) await sleep(DELAY_MS);
	}
	console.info(`✓ Wrote ${flat.length} raw options`);
}

async function waitForEmbeddings(): Promise<void> {
	console.info('Waiting for embedding coverage (fn_statementCreation Task 6)…');
	for (let attempt = 0; attempt < 60; attempt++) {
		const snap = await db.collection('statements').where('parentId', '==', questionId).where('statementType', '==', 'option').get();
		const raw = snap.docs.filter((d) => !d.data().derivedByPipeline);
		const withEmb = raw.filter((d) => {
			const e = d.data().embedding;

			return Array.isArray(e) ? e.length > 0 : !!(e && typeof e === 'object');
		});
		console.info(`  coverage: ${withEmb.length}/${raw.length}`);
		if (raw.length >= 40 && withEmb.length === raw.length) {
			console.info('✓ Full embedding coverage');

			return;
		}
		await sleep(4000);
	}
	console.warn('⚠️ Timed out waiting for full embedding coverage — proceed with caution');
}

(async () => {
	await ensureQuestion();
	await seedOptions();
	await waitForEmbeddings();
	console.info('\nDone. Next: bulkRebuild.ts');
})()
	.then(() => process.exit(0))
	.catch((e) => {
		console.error('clean seed failed:', e);
		process.exit(1);
	});
