import { onDocumentWritten } from 'firebase-functions/v2/firestore';
import { logger } from 'firebase-functions/v1';
import { sheets_v4 } from 'googleapis';
import { db } from '../../db';
import {
	Collections,
	Creator,
	JoinFormConfig,
	JoinFormSubmission,
	JOIN_FORM_SUBMISSIONS_SUBCOLLECTION,
	Statement,
	StatementType,
	functionConfig,
} from '@freedi/shared-types';
import { extractSheetId, getGoogleSheetsClient } from './getGoogleSheetsClient';
import { logError } from '../../utils/errorHandling';
import {
	buildRowFromHeader,
	columnIndexToA1,
	diffMembers as diffMembersPure,
	findRowIndex as findRowIndexPure,
	planV1ToV2Migration,
	type MemberDiff,
	type Role as PureRole,
} from './joinSheetMath';

// Re-export Role from this module for backward compatibility with callers
// that imported it here (e.g. fn_reconcileJoinSheet imports `Role` from
// this file). The pure helpers live in joinSheetMath.ts now.
export type Role = PureRole;

/**
 * Sheet schema (extends the legacy header used by `fn_appendJoinSubmissionToSheet`):
 *   [...formFieldLabels, 'userId', 'displayName', 'role', 'optionId',
 *    'optionTitle', 'submittedAt', 'questionId']
 *
 * The new `optionId` column lets us match rows precisely on remove. Sheets
 * that pre-date this column fall back to (userId, role, optionTitle) for
 * removal so legacy data still works during a transition window.
 */
const METADATA_HEADERS = [
	'userId',
	'displayName',
	'role',
	'optionId',
	'optionTitle',
	'submittedAt',
	'questionId',
] as const;

/**
 * Bump on any breaking schema change (column addition, rename, semantic
 * change). The trigger refuses to write to a sheet whose `Z1` cell shows a
 * higher version — that means the sheet was generated by a newer trigger
 * and writing legacy v2 rows would corrupt it.
 *
 *   v1: legacy 9-col layout (no optionId)
 *   v2: current — adds `optionId` column for precise row matching on remove
 *
 * Old sheets without a Z1 marker are treated as v1 and continue to work via
 * `buildRowFromHeader` adaptation; a warning surfaces in logs so operators
 * can choose to migrate.
 */
export const CURRENT_SHEET_SCHEMA_VERSION = 2;
export const SCHEMA_VERSION_CELL = 'Z1';

/**
 * Drives Google Sheet sync from the option's `joined` and `organizers`
 * arrays — the source of truth in the Join app — instead of from form
 * submissions. This fixes three reported mismatches:
 *
 *   1. User joins option A then option B (same role): the form modal is
 *      cached-skipped, so no second submission write fires. The previous
 *      sheet trigger never knew option B existed.
 *   2. User un-joins option A while still on option B: the previous remove
 *      function deleted the user's only sheet row regardless of which
 *      option they were leaving, wiping them from the sheet entirely.
 *   3. Admin clears `organizers` on an option: sheet rows lingered as
 *      orphans because the sheet was driven by submission docs, not the
 *      option arrays the admin actually edited.
 *
 * Diffing the before/after option doc lets us emit one (append/remove)
 * sheet operation per (user, option, role) transition and keep the sheet
 * in lock-step with the app.
 */
export const fn_syncOptionMembersToSheet = onDocumentWritten(
	{
		document: `${Collections.statements}/{statementId}`,
		region: functionConfig.region,
	},
	async (event) => {
		const { statementId } = event.params;

		try {
			const before = event.data?.before?.exists
				? (event.data.before.data() as Statement | undefined)
				: undefined;
			const after = event.data?.after?.exists
				? (event.data.after.data() as Statement | undefined)
				: undefined;

			// Only react to writes on options. Question docs and other types are
			// ignored — joined/organizers arrays only live on options.
			const subject = after ?? before;
			if (!subject || subject.statementType !== StatementType.option) {
				return null;
			}
			// Cluster docs (topic / hybrid / synthesis) and hidden integrated
			// members are option-typed but carry no real membership state.
			// Skipping them prevents a clustering run from firing this trigger
			// (and reading the parent question doc) on every produced cluster.
			// `integratedInto` is set by performIntegration on hidden members
			// and is not on the shared Statement type, hence the cast.
			const integratedInto = (subject as { integratedInto?: string }).integratedInto;
			if (subject.isCluster === true || integratedInto) {
				return null;
			}

			// Compute membership diffs. If neither array changed, bail out before
			// doing any reads against the question doc or the Sheets API.
			const activistDiff = diffMembers(before?.joined, after?.joined);
			const organizerDiff = diffMembers(before?.organizers, after?.organizers);
			if (
				activistDiff.added.length === 0 &&
				activistDiff.removed.length === 0 &&
				organizerDiff.added.length === 0 &&
				organizerDiff.removed.length === 0
			) {
				return null;
			}

			const questionId = subject.parentId;
			if (!questionId) {
				logger.warn('[fn_syncOptionMembersToSheet] Option has no parentId', {
					statementId,
				});

				return null;
			}

			const questionSnap = await db.collection(Collections.statements).doc(questionId).get();
			if (!questionSnap.exists) {
				return null;
			}
			const question = questionSnap.data() as Statement;
			const joinForm = question.statementSettings?.joinForm;
			if (!joinForm || joinForm.destination !== 'sheets' || !joinForm.sheetUrl) {
				return null;
			}

			const sheetId = extractSheetId(joinForm.sheetUrl);
			if (!sheetId) {
				logger.warn('[fn_syncOptionMembersToSheet] Malformed sheet URL', {
					questionId,
					sheetUrl: joinForm.sheetUrl,
				});

				return null;
			}

			const sheets = getGoogleSheetsClient();
			if (!sheets) {
				logger.warn(
					'[fn_syncOptionMembersToSheet] GOOGLE_SHEETS_SERVICE_ACCOUNT credentials missing',
				);

				return null;
			}

			// Refuse to write if the sheet declares a newer schema than this
			// trigger supports — protects against rolling back the trigger and
			// silently corrupting rows written by a future version.
			const versionOk = await ensureSchemaVersionMatches(sheets, sheetId, questionId);
			if (!versionOk) return null;

			const optionId = subject.statementId;
			const optionTitle = (after ?? before)?.statement ?? '';

			await ensureHeaderRow(sheets, sheetId, joinForm);

			// Auto-migrate v1 sheets in place. Idempotent and cheap on v2 sheets
			// (one Z1 read inside readSheetSchemaVersion + an early exit). Done
			// after `ensureHeaderRow` so brand-new sheets get the v2 header
			// directly and skip the migration path entirely.
			try {
				const version = await readSheetSchemaVersion(sheets, sheetId);
				if (version < CURRENT_SHEET_SCHEMA_VERSION) {
					await migrateV1ToV2IfNeeded(sheets, sheetId, questionId);
				}
			} catch (err) {
				// Migration failure is non-fatal — log and continue with the
				// member sync. Legacy title-matching still works, and the next
				// trigger fire will retry the migration (it's idempotent at the
				// row level via the header check in `planV1ToV2Migration`).
				logger.warn('[fn_syncOptionMembersToSheet] v1→v2 migration step failed', {
					sheetId,
					questionId,
					error: err instanceof Error ? err.message : String(err),
				});
			}

			const additions: Array<{ creator: Creator; role: Role }> = [
				...activistDiff.added.map((c) => ({ creator: c, role: 'activist' as Role })),
				...organizerDiff.added.map((c) => ({ creator: c, role: 'organizer' as Role })),
			];
			const removals: Array<{ uid: string; role: Role }> = [
				...activistDiff.removed.map((c) => ({ uid: c.uid, role: 'activist' as Role })),
				...organizerDiff.removed.map((c) => ({ uid: c.uid, role: 'organizer' as Role })),
			];

			// Process additions first so a same-trigger swap (e.g. activist →
			// organizer on the same option) appends the new row before removing
			// the old — preserves a continuous presence in the sheet.
			for (const { creator, role } of additions) {
				try {
					await appendUserRow({
						sheets,
						sheetId,
						questionId,
						optionId,
						optionTitle,
						userId: creator.uid,
						role,
						joinForm,
					});
				} catch (err) {
					logError(err, {
						operation: 'joinForm.syncOptionMembersToSheet.append',
						userId: creator.uid,
						statementId: optionId,
						metadata: { questionId, role },
					});
				}
			}

			for (const { uid, role } of removals) {
				try {
					await removeUserRow({
						sheets,
						sheetId,
						userId: uid,
						optionId,
						optionTitle,
						role,
					});
				} catch (err) {
					logError(err, {
						operation: 'joinForm.syncOptionMembersToSheet.remove',
						userId: uid,
						statementId: optionId,
						metadata: { questionId, role },
					});
				}
			}

			return null;
		} catch (error) {
			logError(error, {
				operation: 'joinForm.syncOptionMembersToSheet',
				statementId,
			});

			return null;
		}
	},
);

// Local thin wrapper preserves the existing call-sites; the implementation
// now lives in joinSheetMath.ts and is covered by joinSheetMath.test.ts.
function diffMembers(
	beforeArr: Creator[] | undefined,
	afterArr: Creator[] | undefined,
): MemberDiff {
	return diffMembersPure(beforeArr, afterArr);
}

export async function ensureHeaderRow(
	sheets: sheets_v4.Sheets,
	sheetId: string,
	joinForm: JoinFormConfig,
): Promise<void> {
	const existing = await readHeader(sheets, sheetId);
	if (existing.length > 0) {
		return; // Header already present — keep whatever schema is in the sheet.
	}

	const fieldLabels = joinForm.fields.map((f) => f.label);
	await sheets.spreadsheets.values.append({
		spreadsheetId: sheetId,
		range: 'A1',
		valueInputOption: 'USER_ENTERED',
		requestBody: {
			values: [[...fieldLabels, ...METADATA_HEADERS]],
		},
	});

	// Stamp the schema version on a fresh sheet. We use update (not append)
	// at an explicit cell so the version sits at Z1 regardless of how many
	// data columns are in front of it.
	try {
		await sheets.spreadsheets.values.update({
			spreadsheetId: sheetId,
			range: SCHEMA_VERSION_CELL,
			valueInputOption: 'USER_ENTERED',
			requestBody: { values: [[`v${CURRENT_SHEET_SCHEMA_VERSION}`]] },
		});
	} catch (err) {
		// Non-fatal — the sheet still has the right header layout. Operator
		// can hand-set Z1 if the warning ever surfaces.
		logger.warn('[fn_syncOptionMembersToSheet] Could not stamp schema version', {
			sheetId,
			error: err instanceof Error ? err.message : String(err),
		});
	}
}

/**
 * Reads the schema version from `Z1`. Treats missing / non-string / unparseable
 * cells as v1 (legacy) so the trigger keeps working on pre-existing sheets.
 */
export async function readSheetSchemaVersion(
	sheets: sheets_v4.Sheets,
	sheetId: string,
): Promise<number> {
	const resp = await sheets.spreadsheets.values.get({
		spreadsheetId: sheetId,
		range: SCHEMA_VERSION_CELL,
	});
	const cell = resp.data.values?.[0]?.[0];
	if (typeof cell !== 'string') return 1;
	const parsed = Number(cell.replace(/^v/i, '').trim());

	return Number.isFinite(parsed) ? parsed : 1;
}

/**
 * Returns true when it's safe to proceed with writes. Returns false (with a
 * structured log) when the sheet is newer than the trigger supports — the
 * trigger then bails out for this event rather than corrupting the sheet.
 *
 * On older sheets we log a warning but keep going: `buildRowFromHeader`
 * adapts to the live header so v1 sheets continue to work.
 */
async function ensureSchemaVersionMatches(
	sheets: sheets_v4.Sheets,
	sheetId: string,
	questionId: string,
): Promise<boolean> {
	let version: number;
	try {
		version = await readSheetSchemaVersion(sheets, sheetId);
	} catch (err) {
		// If we can't even read Z1, fall through and let the existing sheet
		// reads surface the real error — better than refusing to write on a
		// transient rate-limit hiccup.
		logger.warn('[fn_syncOptionMembersToSheet] Could not read schema version', {
			sheetId,
			questionId,
			error: err instanceof Error ? err.message : String(err),
		});

		return true;
	}

	if (version > CURRENT_SHEET_SCHEMA_VERSION) {
		logger.error(
			'[fn_syncOptionMembersToSheet] Sheet schema version is newer than this trigger supports — refusing to write',
			{
				sheetId,
				questionId,
				sheetVersion: version,
				triggerSupports: CURRENT_SHEET_SCHEMA_VERSION,
			},
		);

		return false;
	}

	if (version < CURRENT_SHEET_SCHEMA_VERSION) {
		logger.warn(
			'[fn_syncOptionMembersToSheet] Sheet predates current schema; relying on header adaptation',
			{
				sheetId,
				questionId,
				sheetVersion: version,
				triggerSupports: CURRENT_SHEET_SCHEMA_VERSION,
			},
		);
	}

	return true;
}

// ---------------------------------------------------------------------------
// v1 → v2 in-place migration
// ---------------------------------------------------------------------------

/**
 * One-shot, in-place v1→v2 migration: appends an `optionId` column at the
 * right edge of the existing header, backfills cells by looking up each
 * row's `optionTitle` against the question's current options, and stamps
 * `Z1 = v2`. Idempotent — re-runs on an already-v2 sheet are a single read
 * and then a no-op.
 *
 * Why APPEND rather than INSERT-in-middle:
 *   - Insert would rewrite every metadata cell; append only writes one
 *     column. Cheaper, less risk of partial-write corruption.
 *   - Human-curated column order (e.g. an admin moved phone before email)
 *     stays intact.
 *
 * Failure handling:
 *   - We stamp Z1 = v2 ONLY after all data writes succeed. A failure
 *     halfway leaves Z1 at v1, so the next trigger fire re-attempts and
 *     `planV1ToV2Migration` skips already-migrated rows by detecting the
 *     `optionId` header.
 *   - Rows whose title couldn't be resolved against current options (e.g.
 *     the option was deleted) get an empty `optionId` cell; the legacy
 *     title-matching path keeps working for them.
 */
export async function migrateV1ToV2IfNeeded(
	sheets: sheets_v4.Sheets,
	sheetId: string,
	questionId: string,
): Promise<void> {
	const meta = await sheets.spreadsheets.get({
		spreadsheetId: sheetId,
		fields: 'sheets(properties(title))',
	});
	const sheetTitle = meta.data.sheets?.[0]?.properties?.title ?? 'Sheet1';
	const valuesResp = await sheets.spreadsheets.values.get({
		spreadsheetId: sheetId,
		range: `${sheetTitle}!A:ZZ`,
	});
	const rawRows = valuesResp.data.values ?? [];
	const rows: string[][] = rawRows.map((r) =>
		(r ?? []).map((c) => (typeof c === 'string' ? c : String(c ?? ''))),
	);

	// Build a `title → optionId` map from live options. We accept stale
	// matches (an option whose title was edited won't match its old rows);
	// those just stay null and keep the legacy match-by-title behavior.
	const optionsSnap = await db
		.collection(Collections.statements)
		.where('parentId', '==', questionId)
		.where('statementType', '==', StatementType.option)
		.get();
	const titleToOptionId = new Map<string, string>();
	for (const od of optionsSnap.docs) {
		const o = od.data() as Statement;
		if (o.isCluster === true) continue;
		const integratedInto = (o as { integratedInto?: string }).integratedInto;
		if (integratedInto) continue;
		const title = (o.statement ?? '').trim();
		if (title && !titleToOptionId.has(title)) {
			titleToOptionId.set(title, o.statementId);
		}
	}

	const plan = planV1ToV2Migration(rows, titleToOptionId);
	if (!plan.needsMigration) {
		// Header already has `optionId` — just make sure Z1 reflects v2 so we
		// stop checking on subsequent fires. (Safe to overwrite — we only get
		// here when readSheetSchemaVersion returned < CURRENT, so Z1 is stale.)
		await stampSchemaVersionV2(sheets, sheetId);

		return;
	}

	const columnLetter = columnIndexToA1(plan.optionIdColumnIndex);
	// Guard: if the new column collides with the Z1 schema marker, refuse
	// to migrate. This only happens on form definitions with 25+ custom
	// fields — extremely rare, but corrupting Z1 would brick the version
	// check forever.
	if (columnLetter === 'Z') {
		logger.error(
			'[fn_syncOptionMembersToSheet] v1→v2 migration would overwrite the Z1 schema marker — refusing',
			{ sheetId, questionId, optionIdColumnIndex: plan.optionIdColumnIndex },
		);

		return;
	}

	// Build the full column: [header, ...row values] aligned with rows[1:].
	// `optionIdsByRow` has one entry per data row in the same order.
	const columnValues: string[][] = [['optionId']];
	for (const v of plan.optionIdsByRow) {
		columnValues.push([v ?? '']);
	}

	const range = `${columnLetter}1:${columnLetter}${columnValues.length}`;
	await sheets.spreadsheets.values.update({
		spreadsheetId: sheetId,
		range,
		valueInputOption: 'RAW',
		requestBody: { values: columnValues },
	});

	await stampSchemaVersionV2(sheets, sheetId);

	const resolved = plan.optionIdsByRow.filter((v) => v !== null).length;
	const unresolved = plan.optionIdsByRow.length - resolved;
	logger.info('[fn_syncOptionMembersToSheet] v1→v2 migration complete', {
		sheetId,
		questionId,
		optionIdColumn: columnLetter,
		rowsMigrated: plan.optionIdsByRow.length,
		resolved,
		unresolved,
	});
}

async function stampSchemaVersionV2(sheets: sheets_v4.Sheets, sheetId: string): Promise<void> {
	await sheets.spreadsheets.values.update({
		spreadsheetId: sheetId,
		range: SCHEMA_VERSION_CELL,
		valueInputOption: 'USER_ENTERED',
		requestBody: { values: [[`v${CURRENT_SHEET_SCHEMA_VERSION}`]] },
	});
}

async function readHeader(sheets: sheets_v4.Sheets, sheetId: string): Promise<string[]> {
	const resp = await sheets.spreadsheets.values.get({
		spreadsheetId: sheetId,
		range: 'A1:ZZ1',
	});
	const row = resp.data.values?.[0] ?? [];

	return row.map((c) => (typeof c === 'string' ? c : ''));
}

export interface AppendArgs {
	sheets: sheets_v4.Sheets;
	sheetId: string;
	questionId: string;
	optionId: string;
	optionTitle: string;
	userId: string;
	role: Role;
	joinForm: JoinFormConfig;
}

export async function appendUserRow(
	args: AppendArgs,
): Promise<'appended' | 'skipped-already-present' | 'skipped-no-submission'> {
	const { sheets, sheetId, questionId, optionId, optionTitle, userId, role, joinForm } = args;

	const submissionSnap = await db
		.collection(Collections.statements)
		.doc(questionId)
		.collection(JOIN_FORM_SUBMISSIONS_SUBCOLLECTION)
		.doc(userId)
		.get();
	if (!submissionSnap.exists) {
		// User joined an option without filling the form (admin-seeded membership,
		// or pre-existing data). Nothing to append — there's no name/contact data.
		logger.info('[fn_syncOptionMembersToSheet] No submission for user, skipping append', {
			questionId,
			optionId,
			userId,
			role,
		});

		return 'skipped-no-submission';
	}
	const submission = submissionSnap.data() as JoinFormSubmission;

	// Skip if a row already exists for this exact (userId, optionId, role) tuple.
	// Protects against retries appending duplicates.
	const existing = await findRowIndex({
		sheets,
		sheetId,
		userId,
		optionId,
		optionTitle,
		role,
	});
	if (existing.rowIndex !== -1) {
		logger.info('[fn_syncOptionMembersToSheet] Row already present, skipping append', {
			questionId,
			optionId,
			userId,
			role,
		});

		return 'skipped-already-present';
	}

	// Build the row keyed off the existing header so values land in the right
	// columns — works for both the legacy 9-column schema (no `optionId`) and
	// the new 10-column schema. Without this, legacy sheets shifted every
	// metadata column one cell to the right (see WhatsApp report 2026-05-09).
	const header = await readHeader(sheets, sheetId);
	const formValues: Record<string, string> = {};
	for (const field of joinForm.fields) {
		formValues[field.label] = submission.values?.[field.id] ?? '';
	}
	const row = buildRowFromHeader(header, {
		userId,
		displayName: submission.displayName ?? '',
		role,
		optionId,
		optionTitle,
		submittedAt: new Date().toISOString(),
		questionId,
		formValues,
	});

	// RAW (not USER_ENTERED) so leading zeros on phone numbers like
	// "0526079419" survive — otherwise Sheets coerces them to integers.
	await sheets.spreadsheets.values.append({
		spreadsheetId: sheetId,
		range: 'A1',
		valueInputOption: 'RAW',
		requestBody: { values: [row] },
	});

	logger.info('[fn_syncOptionMembersToSheet] Appended row', {
		questionId,
		optionId,
		userId,
		role,
	});

	return 'appended';
}

interface RemoveArgs {
	sheets: sheets_v4.Sheets;
	sheetId: string;
	userId: string;
	optionId: string;
	optionTitle: string;
	role: Role;
}

async function removeUserRow(args: RemoveArgs): Promise<void> {
	const { sheets, sheetId, userId, optionId, optionTitle, role } = args;

	const found = await findRowIndex({
		sheets,
		sheetId,
		userId,
		optionId,
		optionTitle,
		role,
	});
	if (found.rowIndex === -1) {
		logger.info('[fn_syncOptionMembersToSheet] No matching row to remove', {
			userId,
			optionId,
			role,
		});

		return;
	}

	await sheets.spreadsheets.batchUpdate({
		spreadsheetId: sheetId,
		requestBody: {
			requests: [
				{
					deleteDimension: {
						range: {
							sheetId: found.sheetTabId,
							dimension: 'ROWS',
							startIndex: found.rowIndex,
							endIndex: found.rowIndex + 1,
						},
					},
				},
			],
		},
	});

	logger.info('[fn_syncOptionMembersToSheet] Removed row', {
		userId,
		optionId,
		role,
		rowNumberInSheet: found.rowIndex + 1,
	});
}

interface FindArgs {
	sheets: sheets_v4.Sheets;
	sheetId: string;
	userId: string;
	optionId: string;
	optionTitle: string;
	role: Role;
}

interface FindResult {
	rowIndex: number; // 0-based; -1 if not found. Header is row 0.
	sheetTabId: number;
}

/**
 * Wraps the pure `findRowIndex` from `joinSheetMath.ts` with the Sheets API
 * I/O. Pure logic stays testable; this function only does the metadata
 * read + values read and delegates the row-matching to the tested helper.
 */
async function findRowIndex(args: FindArgs): Promise<FindResult> {
	const { sheets, sheetId, userId, optionId, optionTitle, role } = args;

	const meta = await sheets.spreadsheets.get({
		spreadsheetId: sheetId,
		fields: 'sheets(properties(sheetId,title))',
	});
	const firstSheet = meta.data.sheets?.[0]?.properties;
	if (!firstSheet || typeof firstSheet.sheetId !== 'number') {
		return { rowIndex: -1, sheetTabId: 0 };
	}
	const sheetTabId = firstSheet.sheetId;
	const sheetTitle = firstSheet.title ?? 'Sheet1';

	const valuesResp = await sheets.spreadsheets.values.get({
		spreadsheetId: sheetId,
		range: `${sheetTitle}!A:ZZ`,
	});
	const rawRows = valuesResp.data.values ?? [];
	const rows: string[][] = rawRows.map((r) =>
		(r ?? []).map((c) => (typeof c === 'string' ? c : String(c ?? ''))),
	);

	const rowIndex = findRowIndexPure(rows, { userId, role, optionId, optionTitle });

	return { rowIndex, sheetTabId };
}
